### ISSUE TITLE
New way to interact with contracts

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#176]
Currently, we only offer a way to interact with a contract via the [GoChain wallet](https://wallet.gochain.io) and to do this, you need to have the ABI. I'm thinking we could provide a very convenient way to interact with a contract by storing the ABI of the contract (the owner can upload it) then people browsing the contract in the explorer can view the data within the contract and interact with it (write transactions). 

# Storing the ABI

* [x] The owner would have to first prove that it's his/her contract (probably?)
* [ ] Upload ABI via a form, we store it in a secondary database (not the one used for the blockchain data, since that one may be blown away and recreated at any time)

# View and interacting with a contract that has an ABI associated with it

When a user views a contract, we check if there's an ABI stored for it and if so:

* [x] Show all single value variables/constants (ones that don't require any input)
* [x] Show a list of functions that do require input
* [x] For read only functions, just show the data
* [x] For transactional functions, user must provide private key, use metamask, etc

Some of this stuff is already in the Wallet and we should probably copy that to start, but this would make it easier and cleaner since the ABI would already exist. We might also consider just merging the two.

**Comment by bergauz** [comment]
@treeder we can get abi from source code that user's gonna send. so 2nd part is a wallet right?

**Comment by treeder** [comment]
Which source code? The source code they use to verify it? That might work I suppose, if someone verifies a contracts code, we could get the API from that and use it, yes.

**Comment by treeder** [comment]
Also, this is a bit different than just the wallet, but it could use the same code. For instance, if I were looking at an ERC20 contract, it could have a "transfer tokens" button which would allow me to transfer those tokens. 

Actually, if an ABI were uploaded and verified, it could just automatically show all the `read only` values, similar to how we show a bunch of them on an ERC20 contract, we could just automatically do the same for any contract. 

Then like in the description, they can interact with it right on the contract page.

**Comment by bergauz** [comment]
@jmank88 @treeder is there any update with this task? @treeder we've talked about if user provides abi and it's valid so we save it to db right?

**Comment by jmank88** [comment]
This appears to have a lot of overlap with other issues.

- I don't think we can/should determine validity of the whole ABI at once, but we can do it per-function.

- If we can "Show all single value variables/constants" automatically, that would be neat.

I think the rest has already been covered.
