### ISSUE TITLE
Extra extra data

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#233]
The 'Extra Data' field is displayed in full, but only the first 32 bytes of vanity data are human readable:
![screenshot from 2019-02-27 11-43-58](https://user-images.githubusercontent.com/1194128/53511050-0e826a00-3a85-11e9-93d3-d6ae081389e4.png)
From https://explorer.gochain.io/block/0x3a5bdb2e1e396ed846dd055d42a625d30446183f5f3f3f180d04b5e5cb99be37

The first 32 vanity bytes should be shown separately.

The rest of the data is not included on every block. We could also consider displaying the full data, but should convert it to a human readable form. The `consensus/clique` package has helper functions for extracting the relevant parts:

- [ExtraVanity](https://godoc.org/github.com/gochain-io/gochain/consensus/clique#ExtraVanity)
- [ExtraHasVote](https://godoc.org/github.com/gochain-io/gochain/consensus/clique#ExtraHasVote)
- [ExtraCandidate](https://godoc.org/github.com/gochain-io/gochain/consensus/clique#ExtraCandidate)
- [ExtraIsVoterElection](https://godoc.org/github.com/gochain-io/gochain/consensus/clique#ExtraIsVoterElection)

Additionally, the `Nonce` field of the header indicates either an auth (`0xffffffffffffffff`) or drop (`0x0000000000000000`) vote. This is the only use for `Nonce`, and it can be removed from its current place in the interface: 
![screenshot from 2019-02-27 11-59-22](https://user-images.githubusercontent.com/1194128/53511982-3b378100-3a87-11e9-95f5-60e41e491238.png)

Ideally, for a regular block we'd see only:

```
Vanity Data: xxxxxx
```

And for a block containing a vote (ExtraHasVote), we'd see:

```
Vanity Data: xxxx
Vote: Authorize/Drop `0x1234` to sign/vote
```

**Comment by jmank88** [comment]
The homepage `Extra Data` column should also only be vanity data (not sure what it is currently).

**Comment by r-gochain** [comment]
![image](https://user-images.githubusercontent.com/40002763/59714894-56d3bc80-921b-11e9-8ebb-e1dc04795cb5.png)
@jmank88 thoughts?

**Comment by jmank88** [comment]
IMHO combining the fields would be much more clear to the users:

> **Vote**
> Add/Remove signer/voter `0x1234`

**Comment by r-gochain** [comment]
@jmank88 so Add remove - it's Nonce (0 or -1)
and signer/voter is from ExtraIsVoterElection?

**Comment by r-gochain** [comment]
and should we show ExtraHasVote in this case?
