### ISSUE TITLE
Fixed Mainnet URLs

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#276]
Shouldn't these URLs be dynamic, for testnet, development, or whatever else?
https://github.com/gochain-io/explorer/blob/d37fe40fc9d07572ccee0c3f7c8f68575e8b4b3d/src/index.html#L10-L18

**Comment by bergauz** [comment]
so there's 2 options:
- add 2nd index.html for testnet
- add SSR (related to #254 )

**Comment by jmank88** [comment]
I don't think a second page for test works because third parties deploy this for their own independent public or private networks, so it needs to be dynamic. For SSR, can't we just use simple golang templates or something, rather than nodejs?

**Comment by jmank88** [comment]
Pulling favicons from gochain.io seems a little strange too.
Can't we just template a single var for all of these?  Who's value is `https://explorer.gochain.io`/`https://testnet-explorer.gochain.io`/`localhost:8080` or whatever custom domain is configured?

**Comment by bergauz** [comment]
> Pulling favicons from gochain.io seems a little strange too.
> Can't we just template a single var for all of these? Who's value is `https://explorer.gochain.io`/`https://testnet-explorer.gochain.io`/`localhost:8080` or whatever custom domain is configured?

fixed

**Comment by bergauz** [comment]
> I don't think a second page for test works because third parties deploy this for their own independent public or private networks, so it needs to be dynamic. For SSR, can't we just use simple golang templates or something, rather than nodejs?

the thing is that it creates random hashes for builded files

**Comment by r-gochain** [comment]
Found only one link - https://github.com/gochain/explorer/blob/62cba819cc5cfe077a1279d1f3528b275cf3a8a4/front/src/index.html#L18 but seems like this one could be ignored (metadata for search engines)
