### ISSUE TITLE
Tx Logs

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#282]
Tx receipts are currently fetched and used for a few fields and statuses. We should also display any receipt logs generated by the tx underneath the input data. This can be just the raw bytes as hex to start, but should eventually be parsed and displayed as solidity events, like in #281.

**Comment by r-gochain** [comment]
![image](https://user-images.githubusercontent.com/40002763/58909709-74356080-871c-11e9-95fc-08a78ba138f7.png)

**Comment by jmank88** [comment]
I would like to keep this open until we support parsing the events too.

**Comment by jmank88** [comment]
Initial version #410 
![Screenshot from 2019-10-14 10-18-25](https://user-images.githubusercontent.com/1194128/66762619-fb81a600-ee6b-11e9-8bde-006617b113e9.png)
