### ISSUE TITLE
Address Tabs

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#309]
This is a collection of tweaks for the `addr` page tabs.

![Screenshot from 2019-05-14 11-20-19](https://user-images.githubusercontent.com/1194128/57714634-8ac72b00-763a-11e9-8d3c-17b8e083d46e.png)

The tab names can be a little confusing, especially `<symbol> Transactions` v.s `Token Transactions`. We could do a few things to make it more clear:

- [x] Move `HOLDERS` left one position, just after `<symbol> TRANSACTIONS` and rename to `<symbol> HOLDERS`
- [x] Rename `<symbol> TRANSACTIONS` to `<symbol> TRANSFERS`
- [ ] Hide `TOKEN TRANSACTIONS` when there is no data (at least for contracts, but maybe for regular accounts too); rename `TOKEN TRANSFERS`
- [x] Move `OWNED TOKENS` after `TOKEN TRANSFERS`; rename to `TOKENS HELD`?; show for contracts also
- [x] Add a brief description (style: centered) at the top of each tab describing what the data is:
 - `TRANSACTIONS`: Transactions to and from this account.
 - `<symbol> TRANSFERS`: Internal `<symbol>` token transfers.
 - `<symbol> HOLDERS`: Balances of accounts holding `<symbol>` tokens.
 - `TOKEN TRANSFERS`: Token transfers to and from this account.
 - `TOKENS HELD`: Balance of tokens held by this account.
 - `INTERACT` and `CONTRACT SOURCE` maybe don't need any description.
- [ ] Related/optional: consider a more wrappable tab selector, like radio pill buttons, since it's getting pretty wide for mobile

**Comment by treeder** [comment]
That confuses me too. Could we just put them all under one "transactions" tab?

**Comment by jmank88** [comment]
They are all fundamentally very different.

**Comment by treeder** [comment]
Why? They're all related to some single transaction.

**Comment by jmank88** [comment]
Transactions is any tx to/from this address.

<symbol> Transactions is token transfer events emitted by txs to this contract address.

Token Transactions is token transfer events to/from this address emitted by txs to other token contract addresses.

**Comment by jmank88** [comment]
I actually like `<symbol> TRANSFERS` and `TOKEN TRANSFERS` better.

**Comment by treeder** [comment]
Those don't seem too fundamentally different. A transfer is a transfer whether it's from a contract or a person or two a contract or a person. I think we can at least merge the "symbol txes" and "token txes" into one (agree, "transfers" is better). 

The transaction that kicked it off is also the same transaction, no matter which column you look at so couldn't they all be together, but the token transfers just have a bit of extra information in the row like:

![Screenshot 2019-05-14 at 12 59 14 PM](https://user-images.githubusercontent.com/75826/57716953-1b583800-7648-11e9-830d-b4bd9d384c29.png)

Then just merge them all?

**Comment by jmank88** [comment]
I think that the current grouping makes sense from a UX perspective, e.g. someone wants to see all the TURBO transfers, and not have other token transfers involving the TURBO contract mixed in, or any other random txs (non-transfers) that the TURBO owner or others are sending. This grouping also allows us to only display the relevant columns of information, rather than e.g. repeating the same exact `to` address for every single `<symbol> transfer`.

If our goal to to have less top level tabs, then we could have the three txs/transfers nested underneath one tab, and either continue to exist as three independent groups, or have three checkbox style buttons so the user can show/hide whichever ones they want.

**Comment by bergauz** [comment]
About hiding TOKEN TRANSACTIONS if empty, it's bad practice since tabs need to be persistent for good ux

**Comment by jmank88** [comment]
> About hiding TOKEN TRANSACTIONS if empty, it's bad practice since tabs need to be persistent for good ux

That's fine. IIRC I was trying to save space, especially since that tab will generally be empty for contracts.

**Comment by jmank88** [comment]
> About hiding TOKEN TRANSACTIONS if empty, it's bad practice since tabs need to be persistent for good ux

That's fine. IIRC I was trying to save space, especially since that tab will generally be empty for contracts.

**Comment by jmank88** [comment]
Closing since this is mostly fixed and also pretty stale anyways.
