### ISSUE TITLE
Richlist return 500 

### ISSUE THREAD

**Issue by dome** [gochain/explorer#330]
3:01AM INF retrying after error error="Error -32000 (unknown initial allocation)"
3:01AM INF retrying after error error="Error -32000 (unknown initial allocation)"
3:01AM INF retrying after error error="Error -32000 (unknown initial allocation)"
3:01AM INF retrying after error error="Error -32000 (unknown initial allocation)"
3:01AM INF retrying after error error="Error -32000 (unknown initial allocation)"
2019/07/02 03:01:12 [db8c025b649e/u3XfeLlbmb-000544] "GET http://dc5.dc0.us:8080/api/richlist?limit=50&skip=0 HTTP/1.1" from 223.204.248.63:56459 - panic: ru$
time error: invalid memory address or nil pointer dereference
2019/07/02 03:01:12 goroutine 1611 [running]:
runtime/debug.Stack(0xc0007de200, 0xc170c0, 0xc00019e060)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc0007de200, 0x7fd20d4030a8, 0xc000090d40)
        /go/pkg/mod/github.com/go-chi/chi@v4.0.1+incompatible/middleware/recoverer.go:25 +0x9c
panic(0xa5e3c0, 0x1065f90)

**Comment by r-gochain** [comment]
@dome could you share the version you use and the parameters or have you built it by yourself?
I don't see such errors in logs neither on testnet or mainnet

**Comment by dome** [comment]
@r-gochain i user V.4.81 
1. pull from github 
2.  build docker image
3. deploy with docker-compose 
4. connect to my private network (Gochain 3.2.7)

**Comment by r-gochain** [comment]
@dome have you set initial allocation in Gochain? cc @jmank88

**Comment by dome** [comment]
@r-gochain  yes. my network go live for 2 month. now i use exploere old version. and try to upgrade to 0.4.81
https://exp.tch.in.th

**Comment by r-gochain** [comment]
@dome you haven't set initial allocation when you configured Gochain

curl https://rpc.tch.in.th  -H 'content-type: application/json;'  --data-binary '[{"id":"94455d269e0ee68abf391d9923d26b13","jsonrpc":"2.0","method":"eth_genesisAlloc"}]' --compressed
[{"jsonrpc":"2.0","id":"94455d269e0ee68abf391d9923d26b13","error":{"code":-32000,"message":"unknown initial allocation"}}]

**Comment by r-gochain** [comment]
Without initial allocation richlist won't work properly

**Comment by jmank88** [comment]
@dome did you initialize the node with a custom genesis file? Can you share the `"alloc"` section?

**Comment by dome** [comment]
@jmank88  
https://github.com/thaichain/mainnet/blob/master/genesis.json

**Comment by silentresearch** [comment]
I'm having the exact same issue here. explorer supply status api doesn't work - ,"error":{"code":-32000,"message":"unknown initial allocation"}}] 
this is my alloc settings in the genesis.json: 
"alloc": {
    "0xF2cBFB1dd50601610e9c4a699780f14415e84e83": {
      "balance": "0x33b2e3c9fd0803ce8000000"
    }
