### ISSUE TITLE
[bug] On testnet explorer, wallet not showing proper balance

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#345]
Explorer shows proper value on address page, but when opening wallet, shows zero balance.

![wally](https://user-images.githubusercontent.com/75826/63555823-4b409280-c4f7-11e9-8bc0-cec224660d50.png)

**Comment by treeder** [comment]
@bergauz

**Comment by treeder** [comment]
Also, person getting:

```
ERROR: NODE ERROR: {"CODE":-32000,"MESSAGE":"INSUFFICIENT FUNDS FOR GAS * PRICE + VALUE"}
```

Is it using the same network for everything or is it getting mixed up somehow?

**Comment by manamaori** [comment]
yeah having an issue and dont know why... switched to metamask and got an error.. more pics anyway
![testnet-wallet](https://user-images.githubusercontent.com/20309708/63557217-ed19bb00-c59b-11e9-8521-04a0087ca868.png)

![testnet-explorer](https://user-images.githubusercontent.com/20309708/63557229-f86ce680-c59b-11e9-97da-05359b9e132b.png)

![metamask](https://user-images.githubusercontent.com/20309708/63557251-0de21080-c59c-11e9-9489-c7a7c6c00c81.png)

![metamask-error](https://user-images.githubusercontent.com/20309708/63557267-1b979600-c59c-11e9-873d-1979f24383f0.png)

**Comment by bergauz** [comment]
So issue with this code: const provider = Web3.givenProvider || new Web3.providers.HttpProvider(rpcProvider); since we need to support MetaMask, so there's 2 options delete Web3.givenProvider, or somehow check that givenProvider is gochain, but at the end there's no sense for 2nd option

**Comment by treeder** [comment]
I think @r-gochain and @jmank88 added a check to ensure it's connected to GoChain on GOFS, so they can probably fix that here too.

**Comment by r-gochain** [comment]
I'll check, on GOFS we checked network_id, could do the same here
