### ISSUE TITLE
BUG: Can't use wallet functions, getting error

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#352]
![Screenshot 2019-09-02 at 5 46 40 PM](https://user-images.githubusercontent.com/75826/64136907-b3ba2a00-cda9-11e9-80cd-ccb4dd7fa26f.png)

**Comment by r-gochain** [comment]
Works for me here - https://testnet-explorer.gochain.io/addr/0xD6Dd3Ff94f557A8E51Bf4f3678C0155994e640eb?addr_tab=interact
and here https://testnet-explorer.gochain.io/addr/0x9a370724cef4eaf8069608Dd0c9ab727fA38C651?addr_tab=interact


also works from wallet tab - https://testnet-explorer.gochain.io/wallet/account?account_tab=use_contract

**Comment by treeder** [comment]
This seemed to have resolved itself (rpc issue?), but it should still properly show the error to the user, rather than just showing a spinner forever.
