### ISSUE TITLE
Misconfigured MetaMask

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#364]
A misconfigured MetaMask prevents a user from creating a wallet: 
![Screenshot from 2019-09-16 10-23-45](https://user-images.githubusercontent.com/1194128/64970801-1f9d9780-d86c-11e9-8e5f-42f373fde4b2.png)(https://explorer.gochain.io/wallet/create)
If MetaMask is not configured properly, should we fall back to acting as if it were not installed at all? In that case, users would still get this warning alert, but they could create a PK and use the wallet that way, w/o MM.

**Comment by jmank88** [comment]
This also affects contract interaction:
![Screenshot from 2019-09-16 10-38-23](https://user-images.githubusercontent.com/1194128/64971990-1f060080-d86e-11e9-83e3-0ab163b26b8f.png)
In general, we should always still be able to make non-payable 'calls' everywhere. Perhaps by managing a separate web3 provider/instance for each, or just by recovering better when MM won't be useful.

**Comment by r-gochain** [comment]
Works for me (seems like it was fixed)

**Comment by jmank88** [comment]
This behavior has not changed for me.

**Comment by jmank88** [comment]
Navigating to the wallet through the interface does not error in the same way as following a link:
https://explorer.gochain.io/wallet/create
https://testnet-explorer.gochain.io/wallet/create

**Comment by jmank88** [comment]
Fixed by #417
