### ISSUE TITLE
Signers Table Tweaks

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#371]
![Screenshot from 2019-09-18 06-58-10](https://user-images.githubusercontent.com/1194128/65146545-b50e6800-d9e1-11e9-84c2-1bb685ec206d.png)
(https://explorer.gochain.io/signers)

- The 'Blocks' column is sortable - can all columns be sortable? (They are clickable looking on hover, but nothing happens)
- Can 'Blocks' values be right-aligned?
- Can '%' be decimal-aligned (like richlist) to the right? (or regular right-align if equivalent)

**Comment by bergauz** [comment]
closed by #380
