### ISSUE TITLE
Incomplete Tx History

### ISSUE THREAD

**Issue by jmank88** [gochain/explorer#375]
The account [0xAF607821E4A2Fc219D511A1C9eF2836216407304](https://explorer.gochain.io/addr/0xAF607821E4A2Fc219D511A1C9eF2836216407304?addr_tab=transactions) shows a history which does not match the current balance:
![Screenshot from 2019-09-19 10-44-04](https://user-images.githubusercontent.com/1194128/65259537-6b4d7c80-daca-11e9-86ed-c968262e8a11.png)
![Screenshot from 2019-09-19 10-37-27](https://user-images.githubusercontent.com/1194128/65258985-84096280-dac9-11e9-9b7e-ae515f6c2677.png)
Based on direct RPC calls, the balance of `0.096703 GO` is correct, suggesting that the tx history is incorrect. `eth_getTransactionCount` returns 6 for this account, but we only see 5 outgoing txs here, so we appear to be missing an outgoing tx for about `57400 GO`.

**Comment by jmank88** [comment]
It didn't occur to me to check the nonces for the outgoing before, but they are `1-5`, so `0` is missing.

Also, the `/tx/` page for all of these show `Nonce: 0`, so that may be bad data in the DB.

**Comment by jmank88** [comment]
Related: #387

**Comment by r-gochain** [comment]
removed txs with "string" values in the nonce and launched refill (also fixed a bug in grabber), the first pass should be done in next 10-15 hours, after this will launch refill with tx count compare

**Comment by jmank88** [comment]
Tx nonces are still appearing as `0`.

**Comment by r-gochain** [comment]
Yep, cleaned out all 0 txs

**Comment by r-gochain** [comment]
nonces are fine, but still see the same amount of txs (5 instead of 6). enabled tx count check for each block, that could take a long

**Comment by jmank88** [comment]
The new nonce path is now available, so we can go to https://explorer.gochain.io/addr/0xAF607821E4A2Fc219D511A1C9eF2836216407304/tx/0, where I realized that the tx is not actually _missing_, it is just a tx sent `to` the `from` address but presented as an incoming tx.
![Screenshot from 2019-10-24 17-07-55](https://user-images.githubusercontent.com/1194128/67529120-d9b0cc00-f680-11e9-8c7b-ea989c04c6cc.png)
We should add some logic to display this special case differently. A column for nonce (outgoing tx only?) might be nice also.

**Comment by r-gochain** [comment]
Cool
