### ISSUE TITLE
docker-compose up ,failed to get latest block number

### ISSUE THREAD

**Issue by m3shine** [gochain/explorer#468]
console:

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' http://xxx.xxx.xxx.xxx:8545

response:

{"jsonrpc":"2.0","id":67,"result":"0x203cc"}

but!!!!!!!!!!!!!!!
set docker-compose.yaml：
command: "web -u http://xxx.xxx.xxx.xxx:8545

then:

web        | {"severity":"EMERGENCY","timestamp":"2020-07-01T15:32:18.620428532Z","caller":"server/main.go:264","message":"Fatal error","error":"failed to create backend: failed to create erc20 balance client: failed to get latest block number: too many arguments, want at most 0","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"/explorer/server/main.go","line":"264","function":"main.main"},"stacktrace":"main.main\n\t/explorer/server/main.go:264\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by m3shine** [comment]
I found the cause of the error: probably due to a bug in the referenced gochain mod.
gochain/rpc/client.go

func (c *Client) newMessage(method string, paramsIn ...interface{}) (*jsonrpcMessage, error) {
	params, err := json.Marshal(paramsIn)
	if err != nil {
		return nil, err
	}
	return &jsonrpcMessage{Version: "2.0", ID: c.nextID(), Method: method, Params: params}, nil
}

if paramsIn == nil , Marshal result is [null] ,result in  too many arguments error when call some methods eg. eth_blockNumber { "params":[]}

**Comment by jmank88** [comment]
This appears to be due to a bug in the client which was fixed here: https://github.com/gochain/gochain/pull/400
PR #469 upgrades that dependency and should resolve this issue.
