### ISSUE TITLE
Total supply can be wrong on contracts

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#473]
Eg: https://testnet-explorer.gochain.io/addr/0x081777678241a5c8a02f2fa348481e33e027901b?addr_tab=transactions

Total supply should equal exactly the balance and if you call the contract directly, it is.

The function is:

```
function totalSupply() public view returns (uint256) {
        return address(this).balance;
    }
```

**Comment by treeder** [comment]
I notice the transfers and holders are also wrong (ie: missing).

**Comment by r-gochain** [comment]
Could you confirm that it's fixed  (at least the total supply is good)?
The problem is in the address update logic - we fire up update only if address has any activity since the latest update and seems like we missed to flag such activity, I'm looking now how this happened
