### ISSUE TITLE
Total transactions not updating

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#477]
Seems that total transactions number is stuck. 

Been at the same number for a while. 

![Screenshot 2020-09-13 at 12 57 00 PM](https://user-images.githubusercontent.com/75826/93028092-8076c180-f5df-11ea-8838-9d6c9f7295e8.png)

**Comment by r-gochain** [comment]
I can see for sure that it's being updated over time
![image](https://user-images.githubusercontent.com/40002763/93257420-7c949c00-f7a5-11ea-9035-0c5ff9378f4d.png)

**Comment by r-gochain** [comment]
Maybe the problem is that it is being updated every X seconds, not online?
