### ISSUE TITLE
tokens showing under token transfers but not in tokens held

### ISSUE THREAD

**Issue by cryptoperdiem** [gochain/explorer#508]
tranfered tokens to my address - transfer is showing as success however this is not reflected in my balance
![trx](https://user-images.githubusercontent.com/80646864/114541203-4f7e6e00-9c4e-11eb-84e4-19b52bf7b39e.JPG)
![tokens held](https://user-images.githubusercontent.com/80646864/114541207-50170480-9c4e-11eb-90a1-8a3e596aa7a2.JPG)
![tokens trs](https://user-images.githubusercontent.com/80646864/114541208-50170480-9c4e-11eb-88af-3d1cd42a067a.JPG)

**Comment by jmank88** [comment]
@cryptoperdiem Could you provide links to the pages from the screenshots?

**Comment by cryptoperdiem** [comment]
https://explorer.gochain.io/addr/0xfFb65dA86347CCd2f620936943E2855850df6D3F?addr_tab=token_transactions
https://explorer.gochain.io/addr/0xfFb65dA86347CCd2f620936943E2855850df6D3F?addr_tab=owned_tokens
https://explorer.gochain.io/tx/0x9fdb5ccd68925f21f2f4a6bef526e74dbe8ba2adfefbfce0d28a5233a114b770

here you go thanx

**Comment by jmank88** [comment]
Could you elaborate on the problem you are seeing? The OMI token balance looks correct based on my math.

**Comment by cryptoperdiem** [comment]
Sorry to waste your time . My mistake . Got mixed up on truat wallet . Thanx
