### ISSUE TITLE
Value in /token/{hash}/asset/{id}

### ISSUE THREAD

**Issue by aug2uag** [gochain/explorer#533]
I'm minting tokens where GO is added to them yet in the token viewer there's no ability to view the amount of GO associated with a token.

Would it be possible to add a `Value` field similar to found in transactions?

This shouldn't be read from JSON (spoofed) and should be from an additional `TokenAssetComponent` binding (if available) or call (if not available) to be displayed. Maybe display logic to display only if there's > 0 GO there.

**Comment by aug2uag** [comment]
@treeder @jmank88 @rkononov we'd like to promote sales but need to have some way of displaying the data, is there any way for me to know and communicate the feasibility and/or ETA for this feature?

**Comment by treeder** [comment]
An NFT token doesn't have a GO value associated with it. Well, an ERC721/GO721 doesn't anyways. You'll need to provide more details on what you're doing.

**Comment by aug2uag** [comment]
We're applying go on our end, validated the NFT can transfer the GO to
another account. The value is passed in at minting and set to a mapping of
tokenID to msg.value, the minting transaction identifies the exact value of
the transaction. In the end, the NFT does retain the value that is
retrievable and in this way we're utilizing this mechanism to benefit our
users/customers.

Agreed that traditionally this isn't used, but we're doing it on our end
and would be tremendously helpful to show the value when there is any
associated with the NFT.

**Comment by aug2uag** [comment]
@treeder according to the standard primary author [it does conform](https://ethereum.stackexchange.com/a/70116/70167) to the standard ... my non-technical partners and our customer research can't stress enough how much they would appreciate and benefit from, respectively, with such a feature

since no one else is doing it, it's exactly what makes it so awesome imo

**Comment by treeder** [comment]
I'm sure it conforms, but it's not part of the spec so I don't think we could support it out of the box for your specific use case. Do you have a website for your project?  Probably a good idea to show it on your own site/app.

**Comment by aug2uag** [comment]
Yes we do have it on our end yet the benefit can only be actualized if the
value info is contained on the blockchain. It's very important to our use
case for the data to be available from the blockchain.

I tried to experiment and implement this on my own but I couldn't identify
how the "Token" page is rendered on the main branch. There's another
semi-related issue for supporting different MIMEs in Token display. What
makes this non-trivial is:
- few or none ERC721 data from grabber
- merging in or clarifying access to render Token page data

**Comment by aug2uag** [comment]
^^ I should say accessibility to ERC721 transactions in grabber, I don't know how many ERC721 transactions are contained in the dataset; maybe there's a list of contracts that I haven't been able to identify on my own

**Comment by aug2uag** [comment]
@treeder you are correct, there is no spec and my use case assumes a one time deposit, whereas a DAO and/or off-chain operation could deposit more than once over time, thus, nullifying the value from the original minting transaction.

I've [opened a discussion](https://ethereum-magicians.org/t/viewing-staked-tokens-in-nft/7234) that I'm hoping will result in a new spec that may be implemented in the near future.
