### ISSUE TITLE
Add API limits, some users are causing issues

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#534]
Somebody is requesting tons of transactions that go way back which is hurting the database for everyone. I think we may have to have paid accounts at some point to let people abuse the API more, but for the free API, we'll have to restrict it. 

* [x] Limit `skip` param to 100 max
* [x] Anything else we should do?

**Comment by r-gochain** [comment]
seems like it's not the case (added missing index and updated 1 query, seems good)

**Comment by r-gochain** [comment]
and btw they stopped scanning all internal transactions for OMI and get only last 100

**Comment by r-gochain** [comment]
let me deploy the most recent version and check the long running logs

**Comment by jacestark** [comment]
I do a weekly wallet update that I share with the community, I generally don't go through transactions, I just count wallets and holdings and would like to see if the limit could be reconsidered or if there was another way to access the information that I need to be able to continue this update for the community.

**Comment by treeder** [comment]
Can you let us know which endpoint you are using and what parameters?  This fix was to prevent scanning of 10s of thousands of transactions which was causing database issues. It's likely if you are doing this we won't allow this for free anymore as it's a cost we'd have to suck up to both fix it and beef up hardware to pay for it.

**Comment by jacestark** [comment]
Hey Travis,

Thanks for the follow up. Ya that is def not me scanning transaction. I am
not versed in any of this. I literally just go down manually, using the
tabs at the bottom, to where the wallets start at 1 whole OMI token to get
a reading. From there I will do some other wallet counts for the community
that people like, like how many hold exactly one million OMI. But that's
it, I don't go into transaction histories other than on the rare occasion
that one of the top 100 gains or loses a large amount. I do this about once
a week and all manually on the Gochain explorer page.

[image: Screen Shot 2021-11-17 at 1.52.48 PM.png]

**Comment by jacestark** [comment]
Is there any way to still see wallets and holdings beyond the first 2 or 3
pages on the OMI Holders tab? I have no need to actually enter the wallets
and see any transaction history.

**Comment by treeder** [comment]
@r-gochain seems that maybe the entire limit is 100?  Can't get to the second page of transactions.
