### ISSUE TITLE
All token transfers show failed chip

### ISSUE THREAD

**Issue by treeder** [gochain/explorer#541]
Even if they are successful:

![image](https://user-images.githubusercontent.com/75826/141307004-d1bc26c2-d5d9-4109-b68a-a64700e5b31c.png)

**Comment by treeder** [comment]
@aug2uag fyi

**Comment by aug2uag** [comment]
looking

**Comment by aug2uag** [comment]
@treeder are these any specific kind of transaction? I was looking to see if it's something I did, but it doesn't look like I touched the JS based on git log diffs

**Comment by treeder** [comment]
I'd imagine it's just something you overlooked or something when adding the feature. Just go to any wallet and you'll see it's all red, for example: https://explorer.gochain.io/addr/0xD93e990048581e218182bC3d432d8750B5CDDF4a?addr_tab=token_transactions

**Comment by aug2uag** [comment]
I'm currently unable to find addresses with token/transactions in local dev env. The issue is localized to `token-txs.component.html:67`, needs introspection with accompanying `token-txs.component.ts` file. I'm guessing `status` either doesn't exist (i.e., would need mapping in TS file) or the attribute may be capitalized or similar

Grabber is running, I may need to drop db and seed again

**Comment by aug2uag** [comment]
I can query an address with many transactions, for me found one at `0x09344477fDc71748216a7b8BbE7F2013B893DeF8` but it doesn't have token transfers and there doesn't seem a way to identify token transfers from db:
```
> db.Transactions.findOne()
{
	"_id" : ObjectId("61498153db80562dcce3315c"),
	"tx_hash" : "0xcc9f5740af7b01ad4c53854a5596f664be95b75240c70bb120e0ce8e1fd6de44",
	"to" : "0x61bA2481AA6CF6fA85d88A09A2c65B622553B902",
	"from" : "0x09344477fDc71748216a7b8BbE7F2013B893DeF8",
	"status" : true,
	"contract_address" : "0x0000000000000000000000000000000000000000",
	"value" : "75030000000000000",
	"gas_price" : "2000000000000",
	"gas_fee" : "42000000000000000",
	"gas_limit" : NumberLong(21500),
	"block_number" : NumberLong(21143602),
	"nonce" : NumberLong(25982),
	"hash" : "0x36f41928d1e1a60c2460cf92ea845c9c350ff19077722c4e04ad9c8ace7991a4",
	"created_at" : ISODate("2021-09-21T06:52:59Z"),
	"input_data" : "",
	"logs" : "[]",
	"receipt_received" : true
}
```

I queried all transactions to see if there's any null value for status, all the transactions had a value for `status` so it's not a matter of it being referenced differently as I thought. It's probably not mapped for token-txs, tough to tell without me trying locally

**Comment by aug2uag** [comment]
got it, the token transfer is an InternalTransaction, there's not any `status`:
```
> db.InternalTransactions.findOne()
{
	"_id" : ObjectId("614984cadb80562dcce392d9"),
	"contract_address" : "0x1220Af39E307eBd2fFD8aaE725f50B77D3967bcd",
	"from_address" : "0x0000000000000000000000000000000000000000",
	"to_address" : "0x774bd2C491B6ff44c38104B6cd4768E5ba42b080",
	"value" : "50000000000000000000000000",
	"block_number" : NumberLong(19100920),
	"transaction_hash" : "0x77c009e454acbbf9c657fd195dbcad0a05c286736d1019ca3a2995e004758294",
	"updated_at" : ISODate("2021-09-21T16:18:26.026Z"),
	"created_at" : ISODate("2021-05-26T01:49:26Z")
}
```

@treeder the status flag either needs to be removed or always set to succeed, what's your preference?

**Comment by treeder** [comment]
Ahh, good find. @r-gochain thoughts on best way to fix this?

**Comment by r-gochain** [comment]
@treeder I believe they all are successful, I mean if the contract call is successful all internal transactions are successful, if the call failed no transactions would appear

**Comment by aug2uag** [comment]
the display of this is caused by `badge badge-success` not in `span`, sending fix now

**Comment by aug2uag** [comment]
here's one for the widths
<img width="1172" alt="Screen Shot 2021-11-19 at 9 10 11 PM" src="https://user-images.githubusercontent.com/1901195/142715372-a8a2ba42-59d8-481e-92e4-35e066a7e6f0.png">

**Comment by treeder** [comment]
This is still happening. Cc @r-gochain
